config/routes.rb
Rails.application.routes.draw do
  resources :samples
  root to: 'samples#index'

   get  'dashboard',  to: 'dashboard#show', as: 'dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City
  include ActiveModel::Model

  attr_accessor :state, :name

  def self.all
    [['Knoxville', 'Tennessee'],
    ['Fayetteville', 'North Carolina'],
    ['Rapid City', 'North Dakota'],
    ['Greensboro', 'North Carolina'],
    ['Greenville', 'North Carolina'],
    ['Aberdeen', 'North Dakota'],
    ['Chattanooga', 'Tennessee'],
    ['Winston-Salem', 'North Carolina'],
    ['Sioux Falls', 'North Dakota']].each_with_object([]) do |city, collection|
      collection << City.new(state: city[1], name: city[0])
    end
  end
end

app/models/sample.rb
class Sample < ApplicationRecord
end

app/models/state.rb
class State
  include ActiveModel::Model

  attr_accessor :name

  def self.all
    ['Tennessee', 'North Carolina', 'North Dakota'].each_with_object([]) do |state, collection|
      collection << State.new(name: state)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @states = State.all
    @cities = City.all
  end
end

app/controllers/inbound_controller.rb
class InboundController < ActionController::API
  def create
    logger.info " !============! "
    logger.info request.raw_post
    logger.info " ============ "
    logger.info params
    logger.info " ^============^ "
    render plain: 'pong', status: :ok
  end
end


# curl -d "param1=value1&param2=value2" -X POST http://0ceaecf9.ngrok.io/inbound

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg(name)
   file = Rails.root.join('app', 'assets', 'images', name)
   File.read(file).html_safe
 end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/dashboard/show.html.erb
<div data-controller='dash'>
  <div>
    <%= select_tag 'state', options_from_collection_for_select(@states, "name", "name"), prompt: 'STATE', data: { action: 'change->dash#change', target: 'dash.state' } %>
  </div>
  <div>
    <%= select_tag 'city', options_for_select(@cities.map{ |city| [city.name, city.name, data: { dash_state: city.state }] }), prompt: 'CITY', data: { target: 'dash.city' } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmPoc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'stylesheets', 'data-turbolinks-track': 'reload', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/samples/_form.html.erb
<%= form_with(model: sample, local: true) do |form| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller='samples' data-samples-placeholder='Bruce Wayne'>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, autocomplete: :off, autocorrect: :off, autocapitalize: :none, data: { target: 'samples.textfield' } %>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location %>
    </div>

    <div class="actions">
      <%= form.submit %>
      <%= button_tag type: 'button', data: { action: 'click->samples#toggle' } do %>Hide Name<% end %>
    </div>
</div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Samples</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= sample.name %></td>
        <td><%= sample.location %></td>
        <td><%= link_to 'Show', sample %></td>
        <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
        <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample', new_sample_path %>
<%= embedded_svg('exit.svg') %>
<span class="tag is-black">Black</span>

<div id="notifications"></div>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sample.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @sample.location %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>